database:
  image: mongo
  ports:
    - "27017:27017"
mongoex:
  image: mongo-express
  environment:
  - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
  - ME_CONFIG_MONGODB_SERVER=database
  - ME_CONFIG_MONGODB_PORT=27017
  - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
  - ME_CONFIG_MONGODB_AUTH_DATABASE=rapids3
  ports:
  - "8081:8081"
  links:
  - database
